dist: trusty
sudo: required

services:
  - docker

env:
#  - STACK=stacks/sugar77/php56-local-build.yml SUGAR=7.9 PHP=5.6
#  - STACK=stacks/sugar79/php56.yml SUGAR=7.9 PHP=5.6
#  - STACK=stacks/sugar79/php71.yml SUGAR=7.9 PHP=7.1
#  - STACK=stacks/sugar79/php71lb.yml SUGAR=7.9 PHP=7.1
#  - STACK=stacks/sugar79/php71-local-build.yml SUGAR=7.9 PHP=7.1
#  - STACK=stacks/sugar79upgrade/php71.yml SUGAR=7.9 PHP=7.1
#  - STACK=stacks/sugar710/php71.yml SUGAR=7.10 PHP=7.1
  - STACK=stacks/sugar8/php71.yml SUGAR=8.0 PHP=7.1
  - STACK=stacks/sugar8/php71-local-build.yml SUGAR=8.0 PHP=7.1
#  - STACK=stacks/sugar81/php71.yml SUGAR=8.1 PHP=7.1
#  - STACK=stacks/sugar81/php71-local-build.yml SUGAR=8.1 PHP=7.1
  - STACK=stacks/sugar82/php71.yml SUGAR=8.2 PHP=7.1
  - STACK=stacks/sugar82/php71-local-build.yml SUGAR=8.2 PHP=7.1
  - STACK=stacks/sugar83/php71.yml SUGAR=8.3 PHP=7.1
  - STACK=stacks/sugar83/php71-local-build.yml SUGAR=8.3 PHP=7.1
  - STACK=stacks/sugar9/php73.yml SUGAR=9.0 PHP=7.3
  - STACK=stacks/sugar9/php73-local-build.yml SUGAR=9.0 PHP=7.3

before_install:
  - sudo service mysql stop
  - sudo service elasticsearch stop
install:
  - echo "docker.local 127.0.0.1" | sudo tee -a /etc/hosts > /dev/null
  - sudo sysctl -w vm.max_map_count=262144
  - cp -r ./tests/web_tests ./data/app/sugar/
script:
  - ./tests/start.sh $STACK $SUGAR $PHP
  - ./tests/web_tests.sh $STACK $SUGAR $PHP
  - ./tests/stop.sh $STACK $SUGAR $PHP
